"""initial schema

Revision ID: 1b5374a8fad3
Revises: 
Create Date: 2025-07-16 23:18:00.496962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5374a8fad3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_key', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_subtask', sa.Boolean(), nullable=True),
    sa.Column('parent_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_index(op.f('ix_issues_jira_key'), 'issues', ['jira_key'], unique=True)
    op.create_index(op.f('ix_issues_parent_key'), 'issues', ['parent_key'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('issues_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_text', sa.String(), nullable=True),
    sa.Column('summary_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_board_id'), 'sprints', ['board_id'], unique=False)
    op.create_index(op.f('ix_sprints_id'), 'sprints', ['id'], unique=False)
    op.create_index(op.f('ix_sprints_jira_id'), 'sprints', ['jira_id'], unique=True)
    op.create_index(op.f('ix_sprints_name'), 'sprints', ['name'], unique=False)
    op.create_table('sprint_issues',
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sprint_id', 'issue_id'),
    sa.UniqueConstraint('sprint_id', 'issue_id', name='uq_sprint_issue')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprint_issues')
    op.drop_index(op.f('ix_sprints_name'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_jira_id'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_id'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_board_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_issues_parent_key'), table_name='issues')
    op.drop_index(op.f('ix_issues_jira_key'), table_name='issues')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
