"""add issues_synced to sprint

Revision ID: d3ec9d2d51e5
Revises: 9d4fdd033241
Create Date: 2025-07-15 21:21:10.565709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ec9d2d51e5'
down_revision: Union[str, Sequence[str], None] = '9d4fdd033241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('issues_synced', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_sprints_issues_synced'), 'sprints', ['issues_synced'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sprints_issues_synced'), table_name='sprints')
    op.drop_column('sprints', 'issues_synced')
    # ### end Alembic commands ###
